export const FETCH_DETAIL_ORDER = 'FETCH_DETAIL_ORDER';
export const FETCH_DETAIL_ORDER_SUCCEEDED = 'FETCH_DETAIL_ORDER_SUCCEEDED';
export const FETCH_DETAIL_ORDER_FAILED = 'FETCH_DETAIL_ORDER_FAILED';

