export const FETCH_DETAIL_ORDER = 'FETCH_DETAIL_ORDER';
export const FETCH_DETAIL_ORDER_SUCCEEDED = 'FETCH_DETAIL_ORDER_SUCCEEDED';
export const FETCH_DETAIL_ORDER_FAILED = 'FETCH_DETAIL_ORDER_FAILED';

export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CONFIRM_ORDER_SUCCEEDED = 'CONFIRM_ORDER_SUCCEEDED';
export const CONFIRM_ORDER_FAILED = 'CONFIRM_ORDER_FAILED';

export const RESET_PROPS_STEP_INDICATOR = 'RESET_PROPS_STEP_INDICATOR';

export const RESET_PROPS_CONFIRM = 'RESET_PROPS_CONFIRM';