export const LOGIN = 'LOGIN';
export const LOGIN_RESULTS = 'LOGIN_RESULTS';

export const ADD_ACCOUNT_INTO_LOCAL = 'ADD_ACCOUNT_INTO_LOCAL';
export const ADD_ACCOUNT_INTO_LOCAL_RESULTS = 'ADD_ACCOUNT_INTO_LOCAL_RESULTS';
