export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ADD_ACCOUNT_INTO_LOCAL = 'ADD_ACCOUNT_INTO_LOCAL';
export const ADD_ACCOUNT_INTO_LOCAL_SUCCEEDED = 'ADD_ACCOUNT_INTO_LOCAL_SUCCEEDED';
export const ADD_ACCOUNT_INTO_LOCAL_FAILED = 'ADD_ACCOUNT_INTO_LOCAL_FAILED';

export const RESET_PROPS_LOGIN = 'RESET_PROPS_LOGIN';
export const RESET_PROPS_MESSAGE_LOGIN = 'RESET_PROPS_MESSAGE_LOGIN';
