export const FETCH_LIST_CONVERSATION = 'FETCH_LIST_CONVERSATION';
export const FETCH_LIST_CONVERSATION_SUCCEEDED = 'FETCH_LIST_CONVERSATION_SUCCEEDED';
export const FETCH_LIST_CONVERSATION_FAILED = 'FETCH_LIST_CONVERSATION_FAILED';

export const RESET_PROPS_MAIN = 'RESET_PROPS_MAIN';
export const RESET_PROPS_MESSAGE_MAIN = 'RESET_PROPS_MESSAGE_MAIN';
export const RESET_PROPS_LIST_CONVERSATION = 'RESET_PROPS_LIST_CONVERSATION';
export const RESET_PROPS_MESSAGE_LIST_CONVERSATION = 'RESET_PROPS_MESSAGE_LIST_CONVERSATION';
export const RESET_PROPS_ITEM_CONVERSATION = 'RESET_PROPS_ITEM_CONVERSATION';
export const RESET_PROPS_MESSAGE_ITEM_CONVERSATION = 'RESET_PROPS_MESSAGE_ITEM_CONVERSATION';

export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION';
export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION_SUCCEEDED = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION_SUCCEEDED';
export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION_FAILED = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_CONVERSATION_FAILED';