export const FETCH_STRANGER_LIST = 'FETCH_STRANGER_LIST';
export const FETCH_STRANGER_LIST_SUCCEEDED = 'FETCH_STRANGER_LIST_SUCCEEDED';
export const FETCH_STRANGER_LIST_FAILED = 'FETCH_STRANGER_LIST_FAILED';

export const RESET_PROPS_STRANGER = 'RESET_PROPS_STRANGER';
export const RESET_PROPS_MESSAGE_STRANGER = 'RESET_PROPS_MESSAGE_STRANGER';