export const FETCH_INVITE_LIST = 'FETCH_INVITE_LIST';
export const FETCH_INVITE_LIST_SUCCEEDED = 'FETCH_INVITE_LIST_SUCCEEDED';
export const FETCH_INVITE_LIST_FAILED = 'FETCH_INVITE_LIST_FAILED';

export const RESET_PROPS_INVITE = 'RESET_PROPS_INVITE';
export const RESET_PROPS_MESSAGE_INVITE = 'RESET_PROPS_MESSAGE_INVITE';
