export const UPDATE_FRIEND_LIST = 'UPDATE_FRIEND_LIST';
export const UPDATE_FRIEND_LIST_SUCCEEDED = 'UPDATE_FRIEND_LIST_SUCCEEDED';
export const UPDATE_FRIEND_LIST_FAILED = 'UPDATE_FRIEND_LIST_FAILED';

export const FETCH_FRIEND_LIST = 'FETCH_FRIEND_LIST';
export const FETCH_FRIEND_LIST_SUCCEEDED = 'FETCH_FRIEND_LIST_SUCCEEDED';
export const FETCH_FRIEND_LIST_FAILED = 'FETCH_FRIEND_LIST_FAILED';

export const RESET_PROPS_FRIEND = 'RESET_PROPS_FRIEND';
export const RESET_PROPS_MESSAGE_FRIEND = 'RESET_PROPS_MESSAGE_FRIEND';