export const REGISTER_RESTAURANT = 'REGISTER_RESTAURANT';
export const REGISTER_RESTAURANT_FAILED = 'REGISTER_RESTAURANT_FAILED';
export const REGISTER_RESTAURANT_SUCCEEDED = 'REGISTER_RESTAURANT_SUCCEEDED';

export const RESET_PROPS_REGISTER = 'RESET_PROPS_REGISTER';