export const ADD_REVIEW_RESTAURANT = 'ADD_REVIEW_RESTAURANT';
export const ADD_REVIEW_RESTAURANT_SUCCEEDED = 'ADD_REVIEW_RESTAURANT_SUCCEEDED';
export const ADD_REVIEW_RESTAURANT_FAILED = 'ADD_REVIEW_RESTAURANT_FAILED';

export const FETCH_DETAIL_DATA = 'FETCH_DETAIL_DATA';
export const FETCH_DETAIL_SUCCEEDED = 'FETCH_DETAIL_SUCCEEDED';
export const FETCH_DETAIL_FAILED = 'FETCH_DETAIL_FAILED';

export const CHECK_HAS_REVIEW = 'CHECK_HAS_REVIEW';
export const CHECK_HAS_REVIEW_SUCCEEDED = 'CHECK_HAS_REVIEW_SUCCEEDED';
export const CHECK_HAS_REVIEW_FAILED = 'CHECK_HAS_REVIEW_FAILED';

export const RESET_PROPS_MESSAGE_ADD_REVIEW = 'RESET_PROPS_MESSAGE_ADD_REVIEW';

export const UPDATE_REVIEW_RESTAURANT = 'UPDATE_REVIEW_RESTAURANT';
export const UPDATE_REVIEW_RESTAURANT_SUCCEEDED = 'UPDATE_REVIEW_RESTAURANT_SUCCEEDED';
export const UPDATE_REVIEW_RESTAURANT_FAILED = 'UPDATE_REVIEW_RESTAURANT_FAILED';