export const SEARCH_RESTAURANT_AND_CLIENT = 'SEARCH_RESTAURANT_AND_CLIENT';
export const SEARCH_RESTAURANT_AND_CLIENT_SUCCEEDED = 'SEARCH_RESTAURANT_AND_CLIENT_SUCCEEDED';
export const SEARCH_RESTAURANT_AND_CLIENT_FAILED = 'SEARCH_RESTAURANT_AND_CLIENT_FAILED';

export const RESET_PROPS_SEARCH = 'RESET_PROPS_SEARCH';

export const RESET_PROPS_MESSAGE_SEARCH = 'RESET_PROPS_MESSAGE_SEARCH';

export const SEARCH_WITH_TYPE = 'SEARCH_WITH_TYPE';
export const SEARCH_WITH_TYPE_SUCCEEDED = 'SEARCH_WITH_TYPE_SUCCEEDED';
export const SEARCH_WITH_TYPE_FAILED = 'SEARCH_WITH_TYPE_FAILED';
export const RESET_PROPS_SEARCH_MODAL = 'RESET_PROPS_SEARCH_MODAL';
export const RESET_PROPS_MESSAGE_SEARCH_MODAL = 'RESET_PROPS_MESSAGE_SEARCH_MODAL';
