export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export const FETCH_NOTIFICATION_SUCCEEDED = 'FETCH_NOTIFICATION_SUCCEEDED';
export const FETCH_NOTIFICATION_FAILED = 'FETCH_NOTIFICATION_FAILED';