export const FETCH_DETAIL_RESTAURANT = 'FETCH_DETAIL_RESTAURANT';
export const FETCH_DETAIL_RESTAURANT_SUCCEEDED = 'FETCH_DETAIL_RESTAURANT_SUCCEEDED';
export const FETCH_DETAIL_RESTAURANT_FAILED = 'FETCH_DETAIL_RESTAURANT_FAILED';
