export const FETCH_DETAIL_RESTAURANT = 'FETCH_DETAIL_RESTAURANT';
export const FETCH_DETAIL_RESTAURANT_SUCCEEDED = 'FETCH_DETAIL_RESTAURANT_SUCCEEDED';
export const FETCH_DETAIL_RESTAURANT_FAILED = 'FETCH_DETAIL_RESTAURANT_FAILED';

export const FETCH_SCORE_REVIEW_FOR_OVERVIEW = 'FETCH_SCORE_REVIEW_FOR_OVERVIEW';
export const FETCH_SCORE_REVIEW_FOR_OVERVIEW_SUCCEEDED = 'FETCH_SCORE_REVIEW_FOR_OVERVIEW_SUCCEEDED';
export const FETCH_SCORE_REVIEW_FOR_OVERVIEW_FAILED = 'FETCH_SCORE_REVIEW_FOR_OVERVIEW_FAILED';


export const CHECK_FOLLOW_RESTAURANT = 'CHECK_FOLLOW_RESTAURANT';
export const CHECK_FOLLOW_RESTAURANT_SUCCEEDED = 'CHECK_FOLLOW_RESTAURANT_SUCCEEDED';
export const CHECK_FOLLOW_RESTAURANT_FAILED = 'CHECK_FOLLOW_RESTAURANT_FAILED';


export const FOLLOWED_AND_UN_FOLLOWED_RESTAURANT = 'FOLLOWED_AND_UN_FOLLOWED_RESTAURANT';
export const FOLLOWED_AND_UN_FOLLOWED_RESTAURANT_SUCCEEDED = 'FOLLOWED_AND_UN_FOLLOWED_RESTAURANT_SUCCEEDED';
export const FOLLOWED_AND_UN_FOLLOWED_RESTAURANT_FAILED = 'FOLLOWED_AND_UN_FOLLOWED_RESTAURANT_FAILED';


export const RESET_PROPS_MESSAGE_OVERVIEW = 'RESET_PROPS_MESSAGE_OVERVIEW';
export const RESET_PROPS_OVERVIEW = 'RESET_PROPS_OVERVIEW';