export const FETCH_NEARBY_LOCATION_RESTAURANT = 'FETCH_NEARBY_LOCATION_RESTAURANT';
export const FETCH_NEARBY_LOCATION_RESTAURANT_SUCCEEDED = 'FETCH_NEARBY_LOCATION_RESTAURANT_SUCCEEDED';
export const FETCH_NEARBY_LOCATION_RESTAURANT_FAILED = 'FETCH_NEARBY_LOCATION_RESTAURANT_FAILED';

export const FETCH_LOCATION_FRIEND = 'FETCH_LOCATION_FRIEND';
export const FETCH_LOCATION_FRIEND_SUCCEEDED = 'FETCH_LOCATION_FRIEND_SUCCEEDED';
export const FETCH_LOCATION_FRIEND_FAILED = 'FETCH_LOCATION_FRIEND_FAILED';

export const FETCH_LOCATION_STRANGER = 'FETCH_LOCATION_STRANGER';
export const FETCH_LOCATION_STRANGER_SUCCEEDED = 'FETCH_LOCATION_STRANGER_SUCCEEDED';
export const FETCH_LOCATION_STRANGER_FAILED = 'FETCH_LOCATION_STRANGER_FAILED';

export const RESET_PROPS_MAP = 'RESET_PROPS_MAP';
export const RESET_PROPS_MESSAGE_MAP = 'RESET_PROPS_MESSAGE_MAP';