export const ADD_MENU = 'ADD_MENU';
export const ADD_MENU_SUCCEEDED = 'ADD_MENU_SUCCEEDED';
export const ADD_MENU_FAILED = 'ADD_MENU_FAILED';

export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCEEDED = 'FETCH_MENU_SUCCEEDED';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';

export const RESET_PROPS_MENU = 'RESET_PROPS_MENU';
export const RESET_PROPS_MESSAGE_MENU = 'RESET_PROPS_MESSAGE_MENU';
