export const FETCH_LIST_CONFIRM_RESTAURANT = 'FETCH_LIST_CONFIRM_RESTAURANT';
export const FETCH_LIST_CONFIRM_RESTAURANT_RESULTS = 'FETCH_LIST_CONFIRM_RESTAURANT_RESULTS';

export const CONFIRM_AGREE = 'CONFIRM_AGREE';
export const CONFIRM_AGREE_RESULTS = 'CONFIRM_AGREE_RESULTS';

export const CONFIRM_CANCEL = 'CONFIRM_CANCEL';
export const CONFIRM_CANCEL_RESULTS = 'CONFIRM_CANCEL_RESULTS';
