export const ADD_REVIEW_RESTAURANT = 'ADD_REVIEW_RESTAURANT';
export const ADD_REVIEW_RESTAURANT_SUCCEEDED = 'ADD_REVIEW_RESTAURANT_SUCCEEDED';
export const ADD_REVIEW_RESTAURANT_FAILED = 'ADD_REVIEW_RESTAURANT_FAILED';

export const FETCH_LIST_REVIEW_RESTAURANT = 'FETCH_LIST_REVIEW_RESTAURANT';
export const FETCH_LIST_REVIEW_RESTAURANT_SUCCEEDED = 'FETCH_LIST_REVIEW_RESTAURANT_SUCCEEDED';
export const FETCH_LIST_REVIEW_RESTAURANT_FAILED = 'FETCH_LIST_REVIEW_RESTAURANT_FAILED';

export const RESET_PROPS_REVIEW = 'RESET_PROPS_REVIEW';
export const RESET_PROPS_MESSAGE_REVIEW = 'RESET_PROPS_MESSAGE_REVIEW';
