export const FETCH_LIST_ORDER = 'FETCH_LIST_ORDER';
export const FETCH_LIST_ORDER_SUCCEEDED = 'FETCH_LIST_ORDER_SUCCEEDED';
export const FETCH_LIST_ORDER_FAILED = 'FETCH_LIST_ORDER_FAILED';

export const RESET_PROPS = 'RESET_PROPS';