export const FETCH_LIST_ORDER_FOR_ADMIN = 'FETCH_LIST_ORDER_FOR_ADMIN';
export const FETCH_LIST_ORDER_FOR_ADMIN_SUCCEEDED = 'FETCH_LIST_ORDER_FOR_ADMIN_SUCCEEDED';
export const FETCH_LIST_ORDER_FOR_ADMIN_FAILED = 'FETCH_LIST_ORDER_FOR_ADMIN_FAILED';