export const FETCH_LIST_RESTAURANT = 'FETCH_LIST_RESTAURANT';
export const FETCH_LIST_RESTAURANT_SUCCEEDED = 'FETCH_LIST_RESTAURANT_SUCCEEDED';
export const FETCH_LIST_RESTAURANT_FAILED = 'FETCH_LIST_RESTAURANT_FAILED';

export const FETCH_LIST_COFFEE = 'FETCH_LIST_COFFEE';
export const FETCH_LIST_COFFEE_SUCCEEDED = 'FETCH_LIST_COFFEE_SUCCEEDED';
export const FETCH_LIST_COFFEE_FAILED = 'FETCH_LIST_COFFEE_FAILED';


export const FETCH_NEARBY_LOCATION_RESTAURANT_FOR_HOME = 'FETCH_NEARBY_LOCATION_RESTAURANT_FOR_HOME';
export const FETCH_NEARBY_LOCATION_RESTAURANT_SUCCEEDED = 'FETCH_NEARBY_LOCATION_RESTAURANT_SUCCEEDED';
export const FETCH_NEARBY_LOCATION_RESTAURANT_FAILED = 'FETCH_NEARBY_LOCATION_RESTAURANT_FAILED';

