export const FETCH_LIST_RESTAURANT = 'FETCH_LIST_RESTAURANT';
export const FETCH_LIST_RESTAURANT_SUCCEEDED = 'FETCH_LIST_RESTAURANT_SUCCEEDED';
export const FETCH_LIST_RESTAURANT_FAILED = 'FETCH_LIST_RESTAURANT_FAILED';

export const FETCH_LIST_COFFEE = 'FETCH_LIST_COFFEE';
export const FETCH_LIST_COFFEE_SUCCEEDED = 'FETCH_LIST_COFFEE_SUCCEEDED';
export const FETCH_LIST_COFFEE_FAILED = 'FETCH_LIST_COFFEE_FAILED';

export const FETCH_LIST_BAR = 'FETCH_LIST_BAR';
export const FETCH_LIST_BAR_SUCCEEDED = 'FETCH_LIST_BAR_SUCCEEDED';
export const FETCH_LIST_BAR_FAILED = 'FETCH_LIST_BAR_FAILED';
