export const FETCH_LIST_RESTAURANT = 'FETCH_LIST_RESTAURANT';
export const FETCH_LIST_RESTAURANT_SUCCEEDED = 'FETCH_LIST_RESTAURANT_SUCCEEDED';
export const FETCH_LIST_RESTAURANT_FAILED = 'FETCH_LIST_RESTAURANT_FAILED';

