export const FETCH_NEARBY_LOCATION_PLACE_FOR_HOME = 'FETCH_NEARBY_LOCATION_PLACE_FOR_HOME';
export const FETCH_NEARBY_LOCATION_PLACE_FOR_HOME_SUCCEEDED = 'FETCH_NEARBY_LOCATION_PLACE_FOR_HOME_SUCCEEDED';
export const FETCH_NEARBY_LOCATION_PLACE_FOR_HOME_FAILED = 'FETCH_NEARBY_LOCATION_PLACE_FOR_HOME_FAILED';

export const RESET_PROPS_SUGGESTION = 'RESET_PROPS_SUGGESTION';
export const RESET_PROPS_MESSAGE_SUGGESTION = 'RESET_PROPS_MESSAGE_SUGGESTION';

export const FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION = 'FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION';
export const FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION_SUCCEEDED = 'FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION_SUCCEEDED';
export const FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION_FAILED = 'FETCH_STAR_PLACE_FOR_ITEM_SUGGESTION_FAILED';


export const FETCH_PLACE_THE_BEST = 'FETCH_PLACE_THE_BEST';
export const FETCH_PLACE_THE_BEST_SUCCEEDED = 'FETCH_PLACE_THE_BEST_SUCCEEDED';
export const FETCH_PLACE_THE_BEST_FAILED = 'FETCH_PLACE_THE_BEST_FAILED';

export const FETCH_FOOD_THE_BEST = 'FETCH_FOOD_THE_BEST';
export const FETCH_FOOD_THE_BEST_SUCCEEDED = 'FETCH_FOOD_THE_BEST_SUCCEEDED';
export const FETCH_FOOD_THE_BEST_FAILED = 'FETCH_FOOD_THE_BEST_FAILED';
export const FETCH_FOOD_THE_BEST_FOR_MODAL = 'FETCH_FOOD_THE_BEST_FOR_MODAL';
export const FETCH_FOOD_THE_BEST_FOR_MODAL_SUCCEEDED = 'FETCH_FOOD_THE_BEST_FOR_MODAL_SUCCEEDED';
export const FETCH_FOOD_THE_BEST_FOR_MODAL_FAILED = 'FETCH_FOOD_THE_BEST_FOR_MODAL_FAILED';


export const FETCH_PLACE_THE_BEST_FOR_MODAL = 'FETCH_PLACE_THE_BEST_FOR_MODAL';
export const FETCH_PLACE_THE_BEST_FOR_MODAL_SUCCEEDED = 'FETCH_PLACE_THE_BEST_FOR_MODAL_SUCCEEDED';
export const FETCH_PLACE_THE_BEST_FOR_MODAL_FAILED = 'FETCH_PLACE_THE_BEST_FOR_MODAL_FAILED';
