export const FETCH_PLACE_LIST_HAS_ARRIVED = 'FETCH_PLACE_LIST_HAS_ARRIVED';
export const FETCH_PLACE_LIST_HAS_ARRIVED_SUCCEEDED = 'FETCH_PLACE_LIST_HAS_ARRIVED_SUCCEEDED';
export const FETCH_PLACE_LIST_HAS_ARRIVED_FAILED = 'FETCH_PLACE_LIST_HAS_ARRIVED_FAILED';

export const RESET_PROPS_PLACE_LIST = 'RESET_PROPS_PLACE_LIST';
export const RESET_PROPS_MESSAGE_PLACE_LIST = 'RESET_PROPS_MESSAGE_PLACE_LIST';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCEEDED = 'ADD_POST_SUCCEEDED';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';

export const RESET_PROPS_MAIN = 'RESET_PROPS_MAIN';
export const RESET_PROPS_MESSAGE_MAIN = 'RESET_PROPS_MESSAGE_MAIN';

