export const FETCH_LIST_MENU_ORDER = 'FETCH_LIST_MENU_ORDER';
export const FETCH_LIST_MENU_ORDER_SUCCEEDED = 'FETCH_LIST_MENU_ORDER_SUCCEEDED';
export const FETCH_LIST_MENU_ORDER_FAILED = 'FETCH_LIST_MENU_ORDER_FAILED';