export const FETCH_LIST_MENU_ORDER = 'FETCH_LIST_MENU_ORDER';
export const FETCH_LIST_MENU_ORDER_SUCCEEDED = 'FETCH_LIST_MENU_ORDER_SUCCEEDED';
export const FETCH_LIST_MENU_ORDER_FAILED = 'FETCH_LIST_MENU_ORDER_FAILED';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCEEDED = 'ADD_ORDER_SUCCEEDED';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const ON_CHANGE_PAGE = 'ON_CHANGE_PAGE';
export const RESET_PROPS = 'RESET_PROPS';