export const FETCH_LIST_MENU_ORDER = 'FETCH_LIST_MENU_ORDER';
export const FETCH_LIST_MENU_ORDER_SUCCEEDED = 'FETCH_LIST_MENU_ORDER_SUCCEEDED';
export const FETCH_LIST_MENU_ORDER_FAILED = 'FETCH_LIST_MENU_ORDER_FAILED';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCEEDED = 'ADD_ORDER_SUCCEEDED';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const ON_CHANGE_PAGE = 'ON_CHANGE_PAGE';
export const RESET_PROPS_MAIN_ORDER = 'RESET_PROPS_MAIN_ORDER';
export const RESET_PROPS_FORM_TIME_ORDER = 'RESET_PROPS_FORM_TIME_ORDER';
export const RESET_PROPS_FORM_INFO_ORDER = 'RESET_PROPS_FORM_INFO_ORDER';
export const RESET_PROPS_FORM_MENU_ORDER = 'RESET_PROPS_FORM_MENU_ORDER';
export const RESET_PROPS_MESSAGE_ORDER = 'RESET_PROPS_MESSAGE_ORDER';

export const SET_DATE_FOR_FORM_LICH = 'SET_DATE_FOR_FORM_LICH';
export const SET_TIME_FOR_FORM_LICH = 'SET_TIME_FOR_FORM_LICH';