export const FETCH_ACCOUNT_VIEW = 'FETCH_ACCOUNT_VIEW';
export const FETCH_ACCOUNT_VIEW_SUCCEEDED = 'FETCH_ACCOUNT_VIEW_SUCCEEDED';
export const FETCH_ACCOUNT_VIEW_FAILED = 'FETCH_ACCOUNT_VIEW_FAILED';

export const RESET_PROPS_MAIN_PERSON = 'RESET_PROPS_MAIN_PERSON';
export const RESET_PROPS_MESSAGE_MAIN_PERSON = 'RESET_PROPS_MESSAGE_MAIN_PERSON';

export const CHECK_IS_FRIEND = 'CHECK_IS_FRIEND';
export const CHECK_IS_FRIEND_SUCCEEDED = 'CHECK_IS_FRIEND_SUCCEEDED';
export const CHECK_IS_FRIEND_FAILED = 'CHECK_IS_FRIEND_FAILED';

export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_SUCCEEDED = 'ADD_FRIEND_SUCCEEDED';
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED';


export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const REMOVE_FRIEND_SUCCEEDED = 'REMOVE_FRIEND_SUCCEEDED';
export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED';

export const RESET_PROPS_HEADER_PERSON = 'RESET_PROPS_HEADER_PERSON';
export const RESET_PROPS_MESSAGE_HEADER_PERSON = 'RESET_PROPS_MESSAGE_HEADER_PERSON';
