export const FETCH_ACCOUNT_VIEW = 'FETCH_ACCOUNT_VIEW';
export const FETCH_ACCOUNT_VIEW_SUCCEEDED = 'FETCH_ACCOUNT_VIEW_SUCCEEDED';
export const FETCH_ACCOUNT_VIEW_FAILED = 'FETCH_ACCOUNT_VIEW_FAILED';

export const RESET_PROPS_MAIN_PERSON = 'RESET_PROPS_MAIN_PERSON';
export const RESET_PROPS_MESSAGE_MAIN_PERSON = 'RESET_PROPS_MESSAGE_MAIN_PERSON';

export const CHECK_IS_FRIEND = 'CHECK_IS_FRIEND';
export const CHECK_IS_FRIEND_SUCCEEDED = 'CHECK_IS_FRIEND_SUCCEEDED';
export const CHECK_IS_FRIEND_FAILED = 'CHECK_IS_FRIEND_FAILED';

export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_SUCCEEDED = 'ADD_FRIEND_SUCCEEDED';
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED';


export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const REMOVE_FRIEND_SUCCEEDED = 'REMOVE_FRIEND_SUCCEEDED';
export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED';

export const RESET_PROPS_HEADER_PERSON = 'RESET_PROPS_HEADER_PERSON';
export const RESET_PROPS_MESSAGE_HEADER_PERSON = 'RESET_PROPS_MESSAGE_HEADER_PERSON';

export const FETCH_POST_LIST_FOR_PERSON = 'FETCH_POST_LIST_FOR_PERSON';
export const FETCH_POST_LIST_FOR_PERSON_SUCCEEDED = 'FETCH_POST_LIST_FOR_PERSON_SUCCEEDED';
export const FETCH_POST_LIST_FOR_PERSON_FAILED = 'FETCH_POST_LIST_FOR_PERSON_FAILED';

export const RESET_PROPS_POST_LIST = 'RESET_PROPS_POST_LIST';
export const RESET_PROPS_MESSAGE_POST_LIST = 'RESET_PROPS_MESSAGE_POST_LIST';

export const REFRESH_POST_LIST = 'REFRESH_POST_LIST';

export const LIKE_POST_FOR_PERSON = 'LIKE_POST_FOR_PERSON';
export const CHECK_HAS_LIKE_POST_FOR_PERSON = 'CHECK_HAS_LIKE_POST_FOR_PERSON';
export const CHECK_HAS_LIKE_POST_FOR_PERSON_SUCCEEDED = 'CHECK_HAS_LIKE_POST_FOR_PERSON_SUCCEEDED';
export const CHECK_HAS_LIKE_POST_FOR_PERSON_FAILED = 'CHECK_HAS_LIKE_POST_FOR_PERSON_FAILED';


export const RESET_PROPS_ITEM_POST_LIST = 'RESET_PROPS_ITEM_POST_LIST';
export const RESET_PROPS_MESSAGE_ITEM_POST_LIST = 'RESET_PROPS_MESSAGE_ITEM_POST_LIST';

export const ACCESS_PLACE_IN_POST = 'ACCESS_PLACE_IN_POST';
export const REFRESH_COMMENT_REPLY = 'REFRESH_COMMENT_REPLY';

export const CHANGE_STATUS_FRIEND = 'CHANGE_STATUS_FRIEND';