export const FETCH_ACCOUNT_VIEW = 'FETCH_ACCOUNT_VIEW';
export const FETCH_ACCOUNT_VIEW_SUCCEEDED = 'FETCH_ACCOUNT_VIEW_SUCCEEDED';
export const FETCH_ACCOUNT_VIEW_FAILED = 'FETCH_ACCOUNT_VIEW_FAILED';

export const RESET_PROPS_MAIN_PERSON = 'RESET_PROPS_MAIN_PERSON';
export const RESET_PROPS_MESSAGE_MAIN_PERSON = 'RESET_PROPS_MESSAGE_MAIN_PERSON';