export const FETCH_LIST_MESSAGE = 'FETCH_LIST_MESSAGE';
export const FETCH_LIST_MESSAGE_SUCCEEDED = 'FETCH_LIST_MESSAGE_SUCCEEDED';
export const FETCH_LIST_MESSAGE_FAILED = 'FETCH_LIST_MESSAGE_FAILED';

export const RESET_PROPS_LIST_MESSAGE = 'RESET_PROPS_LIST_MESSAGE';
export const RESET_PROPS_MESSAGE_LIST_MESSAGE = 'RESET_PROPS_MESSAGE_LIST_MESSAGE';
export const RESET_PROPS_MAIN = 'RESET_PROPS_MAIN';
export const RESET_PROPS_MESSAGE_MAIN = 'RESET_PROPS_MESSAGE_MAIN';

export const CHECK_CONVERSATION_EXIST = 'CHECK_CONVERSATION_EXIST';
export const CHECK_CONVERSATION_EXIST_SUCCEEDED = 'CHECK_CONVERSATION_EXIST_SUCCEEDED';
export const CHECK_CONVERSATION_EXIST_FAILED = 'CHECK_CONVERSATION_EXIST_FAILED';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT';
export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT_SUCCEEDED = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT_SUCCEEDED';
export const FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT_FAILED = 'FETCH_INFO_ACCOUNT_RECEIVER_FOR_DETAIL_CHAT_FAILED';

export const RECEIVER_MESSAGE_FROM_SERVER = 'RECEIVER_MESSAGE_FROM_SERVER';