export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCEEDED = 'SIGNUP_SUCCEEDED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const RESET_PROPS_SIGNUP = 'RESET_PROPS_SIGNUP';
export const RESET_PROPS_MESSAGE_SIGNUP = 'RESET_PROPS_MESSAGE_SIGNUP';